#!/bin/sh

# Make movement easier, eg.
# `c path/to/dir/like/normal/cd`
# `c path/to/file/also/work`
# `c [`  # cd a separate shell into the same dir
# `c -`  # go back to the last dir you were in, like `cd -` or `popd`


c() {
  local dir="$1"
  local history_file="$HOME/.cd_history"

  if [ "$dir" = "[" ] || [ "$dir" = "]" ]; then
    # go to current working dir
    cd "$(tail -n1 "$history_file")" || return
  elif [ "$dir" = "-" ]; then
    # go back to last visited dir
    cd "$(tail -n2 "$history_file" | head -n1)" || return
  elif [ -f "$dir" ]; then
    # specified a file, go to the containing directory
    cd "$(dirname "$dir")" || return
  elif [ -z "$dir" ]; then
    # no argument
    cd || return
  else
    cd "$dir" || return
  fi

  if [ -n "$HISTSIZE" ]; then
    # record
    echo "$(pwd)" >> "$history_file"

    # dedup and truncate (FIFO)
    tail -n "$HISTSIZE" "$history_file" | tac | awk '!seen[$0]++' | tac > "$history_file.tmp" &&
      mv -f "$history_file.tmp" "$history_file"
  fi

  ls
}


# bash-only: autocomplete dirs, respecting the filter
if [ -n "$BASH_VERSION" ] && [ -n "$DIGNORE" ]; then
  shopt -s extglob
  complete -d -X "*@($(printf '%s' "$DIGNORE" | tr ':' '|'))" -o default c
fi
