#!/bin/sh

# ls++
# set DIGNORE / FIGNORE env vars to filter results

# build regex from ignore lists
_l_regex=$(printf '%s' "$DIGNORE:$FIGNORE" | tr ':' '\n' | grep -v '^$' | paste -sd'|' -)

l() {
  if [ -f "$*" ] ; then
    ls -l "$@"
  elif [ -n "$_l_regex" ]; then
    ls "$@" | grep -v -E "($_l_regex)"
  else
    ls "$@"
  fi
}


# bash-only: autocomplete files/dirs, respecting the filters
if [ -n "$BASH_VERSION" ] && [ -n "$_l_regex" ]; then
  shopt -s extglob
  complete -f -d -X "*@($_l_regex)" l
fi
