#!/bin/sh

# ensure ssh-agent is running and available to this shell


ssh_agent_alive() {
  [ -n "$SSH_AGENT_PID" ] || return 1

  # alive iff a running process with that PID is an ssh-agent
  ps -p "$SSH_AGENT_PID" -o comm= 2>/dev/null | grep -q ssh-agent
}


# if PID is defined, make sure agent is actually running
if [ -n "$SSH_AGENT_PID" ]; then
  if ! ssh_agent_alive; then
    echo 'ssh-agent: invalid PID'
    # agent is dead
    unset SSH_AGENT_PID
  fi
fi


# try to connect to existing ssh agent
if [ -z "$SSH_AGENT_PID" ]; then
  if [ -f ~/.ssh/env ]; then
    . ~/.ssh/env

    if ! ssh_agent_alive; then
      echo 'ssh-agent: ssh env file is stale'
      rm ~/.ssh/env
      unset SSH_AGENT_PID
    fi
  fi
fi


# start up a new agent and save env vars
if [ -z "$SSH_AGENT_PID" ]; then
    echo 'ssh-agent: starting new agent'

    ssh-agent | grep -v echo > ~/.ssh/env
    chmod 600 ~/.ssh/env
    . ~/.ssh/env

    # load keys
    ssh-add
fi


# tidy up
unset -f ssh_agent_alive

# echo $SSH_AGENT_PID
# echo $SSH_AUTH_SOCK
